# TCL File Generated by Component Editor 25.1
# Tue Mar 31 13:17:02 CDT 2026
# DO NOT MODIFY


# 
# axi_lite_pwm "AXI Lite PWM" v1.0
# Eder Torres 2026.03.31.13:17:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi_lite_pwm
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_lite_pwm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Eder Torres"
set_module_property DISPLAY_NAME "AXI Lite PWM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

