// system.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module system (
		input  wire  clk_clk,         //     clk.clk
		output wire  pwm_out_conduit, // pwm_out.conduit
		input  wire  reset_reset_n    //   reset.reset_n
	);

	wire  [31:0] niosv_m_data_manager_awaddr;                               // niosv_m:data_manager_awaddr -> mm_interconnect_0:niosv_m_data_manager_awaddr
	wire   [1:0] niosv_m_data_manager_bresp;                                // mm_interconnect_0:niosv_m_data_manager_bresp -> niosv_m:data_manager_bresp
	wire         niosv_m_data_manager_arready;                              // mm_interconnect_0:niosv_m_data_manager_arready -> niosv_m:data_manager_arready
	wire  [31:0] niosv_m_data_manager_rdata;                                // mm_interconnect_0:niosv_m_data_manager_rdata -> niosv_m:data_manager_rdata
	wire   [3:0] niosv_m_data_manager_wstrb;                                // niosv_m:data_manager_wstrb -> mm_interconnect_0:niosv_m_data_manager_wstrb
	wire         niosv_m_data_manager_wready;                               // mm_interconnect_0:niosv_m_data_manager_wready -> niosv_m:data_manager_wready
	wire         niosv_m_data_manager_awready;                              // mm_interconnect_0:niosv_m_data_manager_awready -> niosv_m:data_manager_awready
	wire         niosv_m_data_manager_rready;                               // niosv_m:data_manager_rready -> mm_interconnect_0:niosv_m_data_manager_rready
	wire         niosv_m_data_manager_bready;                               // niosv_m:data_manager_bready -> mm_interconnect_0:niosv_m_data_manager_bready
	wire         niosv_m_data_manager_wvalid;                               // niosv_m:data_manager_wvalid -> mm_interconnect_0:niosv_m_data_manager_wvalid
	wire  [31:0] niosv_m_data_manager_araddr;                               // niosv_m:data_manager_araddr -> mm_interconnect_0:niosv_m_data_manager_araddr
	wire   [2:0] niosv_m_data_manager_arprot;                               // niosv_m:data_manager_arprot -> mm_interconnect_0:niosv_m_data_manager_arprot
	wire   [1:0] niosv_m_data_manager_rresp;                                // mm_interconnect_0:niosv_m_data_manager_rresp -> niosv_m:data_manager_rresp
	wire   [2:0] niosv_m_data_manager_awprot;                               // niosv_m:data_manager_awprot -> mm_interconnect_0:niosv_m_data_manager_awprot
	wire  [31:0] niosv_m_data_manager_wdata;                                // niosv_m:data_manager_wdata -> mm_interconnect_0:niosv_m_data_manager_wdata
	wire         niosv_m_data_manager_arvalid;                              // niosv_m:data_manager_arvalid -> mm_interconnect_0:niosv_m_data_manager_arvalid
	wire         niosv_m_data_manager_bvalid;                               // mm_interconnect_0:niosv_m_data_manager_bvalid -> niosv_m:data_manager_bvalid
	wire         niosv_m_data_manager_awvalid;                              // niosv_m:data_manager_awvalid -> mm_interconnect_0:niosv_m_data_manager_awvalid
	wire         niosv_m_data_manager_rvalid;                               // mm_interconnect_0:niosv_m_data_manager_rvalid -> niosv_m:data_manager_rvalid
	wire  [31:0] niosv_m_instruction_manager_awaddr;                        // niosv_m:instruction_manager_awaddr -> mm_interconnect_0:niosv_m_instruction_manager_awaddr
	wire   [1:0] niosv_m_instruction_manager_bresp;                         // mm_interconnect_0:niosv_m_instruction_manager_bresp -> niosv_m:instruction_manager_bresp
	wire         niosv_m_instruction_manager_arready;                       // mm_interconnect_0:niosv_m_instruction_manager_arready -> niosv_m:instruction_manager_arready
	wire  [31:0] niosv_m_instruction_manager_rdata;                         // mm_interconnect_0:niosv_m_instruction_manager_rdata -> niosv_m:instruction_manager_rdata
	wire   [3:0] niosv_m_instruction_manager_wstrb;                         // niosv_m:instruction_manager_wstrb -> mm_interconnect_0:niosv_m_instruction_manager_wstrb
	wire         niosv_m_instruction_manager_wready;                        // mm_interconnect_0:niosv_m_instruction_manager_wready -> niosv_m:instruction_manager_wready
	wire         niosv_m_instruction_manager_awready;                       // mm_interconnect_0:niosv_m_instruction_manager_awready -> niosv_m:instruction_manager_awready
	wire         niosv_m_instruction_manager_rready;                        // niosv_m:instruction_manager_rready -> mm_interconnect_0:niosv_m_instruction_manager_rready
	wire         niosv_m_instruction_manager_bready;                        // niosv_m:instruction_manager_bready -> mm_interconnect_0:niosv_m_instruction_manager_bready
	wire         niosv_m_instruction_manager_wvalid;                        // niosv_m:instruction_manager_wvalid -> mm_interconnect_0:niosv_m_instruction_manager_wvalid
	wire  [31:0] niosv_m_instruction_manager_araddr;                        // niosv_m:instruction_manager_araddr -> mm_interconnect_0:niosv_m_instruction_manager_araddr
	wire   [2:0] niosv_m_instruction_manager_arprot;                        // niosv_m:instruction_manager_arprot -> mm_interconnect_0:niosv_m_instruction_manager_arprot
	wire   [1:0] niosv_m_instruction_manager_rresp;                         // mm_interconnect_0:niosv_m_instruction_manager_rresp -> niosv_m:instruction_manager_rresp
	wire   [2:0] niosv_m_instruction_manager_awprot;                        // niosv_m:instruction_manager_awprot -> mm_interconnect_0:niosv_m_instruction_manager_awprot
	wire  [31:0] niosv_m_instruction_manager_wdata;                         // niosv_m:instruction_manager_wdata -> mm_interconnect_0:niosv_m_instruction_manager_wdata
	wire         niosv_m_instruction_manager_arvalid;                       // niosv_m:instruction_manager_arvalid -> mm_interconnect_0:niosv_m_instruction_manager_arvalid
	wire         niosv_m_instruction_manager_bvalid;                        // mm_interconnect_0:niosv_m_instruction_manager_bvalid -> niosv_m:instruction_manager_bvalid
	wire         niosv_m_instruction_manager_awvalid;                       // niosv_m:instruction_manager_awvalid -> mm_interconnect_0:niosv_m_instruction_manager_awvalid
	wire         niosv_m_instruction_manager_rvalid;                        // mm_interconnect_0:niosv_m_instruction_manager_rvalid -> niosv_m:instruction_manager_rvalid
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:jtag_uart_avalon_jtag_slave_chipselect -> jtag_uart:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;    // jtag_uart:av_readdata -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest; // jtag_uart:av_waitrequest -> mm_interconnect_0:jtag_uart_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;     // mm_interconnect_0:jtag_uart_avalon_jtag_slave_address -> jtag_uart:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;        // mm_interconnect_0:jtag_uart_avalon_jtag_slave_read -> jtag_uart:av_read_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;       // mm_interconnect_0:jtag_uart_avalon_jtag_slave_write -> jtag_uart:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:jtag_uart_avalon_jtag_slave_writedata -> jtag_uart:av_writedata
	wire  [31:0] mm_interconnect_0_niosv_m_dm_agent_readdata;               // niosv_m:dm_agent_readdata -> mm_interconnect_0:niosv_m_dm_agent_readdata
	wire         mm_interconnect_0_niosv_m_dm_agent_waitrequest;            // niosv_m:dm_agent_waitrequest -> mm_interconnect_0:niosv_m_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_niosv_m_dm_agent_address;                // mm_interconnect_0:niosv_m_dm_agent_address -> niosv_m:dm_agent_address
	wire         mm_interconnect_0_niosv_m_dm_agent_read;                   // mm_interconnect_0:niosv_m_dm_agent_read -> niosv_m:dm_agent_read
	wire         mm_interconnect_0_niosv_m_dm_agent_readdatavalid;          // niosv_m:dm_agent_readdatavalid -> mm_interconnect_0:niosv_m_dm_agent_readdatavalid
	wire         mm_interconnect_0_niosv_m_dm_agent_write;                  // mm_interconnect_0:niosv_m_dm_agent_write -> niosv_m:dm_agent_write
	wire  [31:0] mm_interconnect_0_niosv_m_dm_agent_writedata;              // mm_interconnect_0:niosv_m_dm_agent_writedata -> niosv_m:dm_agent_writedata
	wire         mm_interconnect_0_onchip_memory_s2_chipselect;             // mm_interconnect_0:onchip_memory_s2_chipselect -> onchip_memory:chipselect2
	wire  [31:0] mm_interconnect_0_onchip_memory_s2_readdata;               // onchip_memory:readdata2 -> mm_interconnect_0:onchip_memory_s2_readdata
	wire  [14:0] mm_interconnect_0_onchip_memory_s2_address;                // mm_interconnect_0:onchip_memory_s2_address -> onchip_memory:address2
	wire   [3:0] mm_interconnect_0_onchip_memory_s2_byteenable;             // mm_interconnect_0:onchip_memory_s2_byteenable -> onchip_memory:byteenable2
	wire         mm_interconnect_0_onchip_memory_s2_write;                  // mm_interconnect_0:onchip_memory_s2_write -> onchip_memory:write2
	wire  [31:0] mm_interconnect_0_onchip_memory_s2_writedata;              // mm_interconnect_0:onchip_memory_s2_writedata -> onchip_memory:writedata2
	wire         mm_interconnect_0_onchip_memory_s2_clken;                  // mm_interconnect_0:onchip_memory_s2_clken -> onchip_memory:clken2
	wire  [11:0] mm_interconnect_0_axi_lite_pwm_s_axil_awaddr;              // mm_interconnect_0:axi_lite_pwm_s_axil_awaddr -> axi_lite_pwm:s_axil_awaddr
	wire   [1:0] mm_interconnect_0_axi_lite_pwm_s_axil_bresp;               // axi_lite_pwm:s_axil_bresp -> mm_interconnect_0:axi_lite_pwm_s_axil_bresp
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_arready;             // axi_lite_pwm:s_axil_arready -> mm_interconnect_0:axi_lite_pwm_s_axil_arready
	wire  [31:0] mm_interconnect_0_axi_lite_pwm_s_axil_rdata;               // axi_lite_pwm:s_axil_rdata -> mm_interconnect_0:axi_lite_pwm_s_axil_rdata
	wire   [3:0] mm_interconnect_0_axi_lite_pwm_s_axil_wstrb;               // mm_interconnect_0:axi_lite_pwm_s_axil_wstrb -> axi_lite_pwm:s_axil_wstrb
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_wready;              // axi_lite_pwm:s_axil_wready -> mm_interconnect_0:axi_lite_pwm_s_axil_wready
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_awready;             // axi_lite_pwm:s_axil_awready -> mm_interconnect_0:axi_lite_pwm_s_axil_awready
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_rready;              // mm_interconnect_0:axi_lite_pwm_s_axil_rready -> axi_lite_pwm:s_axil_rready
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_bready;              // mm_interconnect_0:axi_lite_pwm_s_axil_bready -> axi_lite_pwm:s_axil_bready
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_wvalid;              // mm_interconnect_0:axi_lite_pwm_s_axil_wvalid -> axi_lite_pwm:s_axil_wvalid
	wire  [11:0] mm_interconnect_0_axi_lite_pwm_s_axil_araddr;              // mm_interconnect_0:axi_lite_pwm_s_axil_araddr -> axi_lite_pwm:s_axil_araddr
	wire   [1:0] mm_interconnect_0_axi_lite_pwm_s_axil_rresp;               // axi_lite_pwm:s_axil_rresp -> mm_interconnect_0:axi_lite_pwm_s_axil_rresp
	wire  [31:0] mm_interconnect_0_axi_lite_pwm_s_axil_wdata;               // mm_interconnect_0:axi_lite_pwm_s_axil_wdata -> axi_lite_pwm:s_axil_wdata
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_arvalid;             // mm_interconnect_0:axi_lite_pwm_s_axil_arvalid -> axi_lite_pwm:s_axil_arvalid
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_bvalid;              // axi_lite_pwm:s_axil_bvalid -> mm_interconnect_0:axi_lite_pwm_s_axil_bvalid
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_awvalid;             // mm_interconnect_0:axi_lite_pwm_s_axil_awvalid -> axi_lite_pwm:s_axil_awvalid
	wire         mm_interconnect_0_axi_lite_pwm_s_axil_rvalid;              // axi_lite_pwm:s_axil_rvalid -> mm_interconnect_0:axi_lite_pwm_s_axil_rvalid
	wire  [31:0] mm_interconnect_0_niosv_m_timer_sw_agent_readdata;         // niosv_m:timer_sw_agent_readdata -> mm_interconnect_0:niosv_m_timer_sw_agent_readdata
	wire         mm_interconnect_0_niosv_m_timer_sw_agent_waitrequest;      // niosv_m:timer_sw_agent_waitrequest -> mm_interconnect_0:niosv_m_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_niosv_m_timer_sw_agent_address;          // mm_interconnect_0:niosv_m_timer_sw_agent_address -> niosv_m:timer_sw_agent_address
	wire         mm_interconnect_0_niosv_m_timer_sw_agent_read;             // mm_interconnect_0:niosv_m_timer_sw_agent_read -> niosv_m:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_niosv_m_timer_sw_agent_byteenable;       // mm_interconnect_0:niosv_m_timer_sw_agent_byteenable -> niosv_m:timer_sw_agent_byteenable
	wire         mm_interconnect_0_niosv_m_timer_sw_agent_readdatavalid;    // niosv_m:timer_sw_agent_readdatavalid -> mm_interconnect_0:niosv_m_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_niosv_m_timer_sw_agent_write;            // mm_interconnect_0:niosv_m_timer_sw_agent_write -> niosv_m:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_niosv_m_timer_sw_agent_writedata;        // mm_interconnect_0:niosv_m_timer_sw_agent_writedata -> niosv_m:timer_sw_agent_writedata
	wire         mm_interconnect_0_onchip_memory_s1_chipselect;             // mm_interconnect_0:onchip_memory_s1_chipselect -> onchip_memory:chipselect
	wire  [31:0] mm_interconnect_0_onchip_memory_s1_readdata;               // onchip_memory:readdata -> mm_interconnect_0:onchip_memory_s1_readdata
	wire  [14:0] mm_interconnect_0_onchip_memory_s1_address;                // mm_interconnect_0:onchip_memory_s1_address -> onchip_memory:address
	wire   [3:0] mm_interconnect_0_onchip_memory_s1_byteenable;             // mm_interconnect_0:onchip_memory_s1_byteenable -> onchip_memory:byteenable
	wire         mm_interconnect_0_onchip_memory_s1_write;                  // mm_interconnect_0:onchip_memory_s1_write -> onchip_memory:write
	wire  [31:0] mm_interconnect_0_onchip_memory_s1_writedata;              // mm_interconnect_0:onchip_memory_s1_writedata -> onchip_memory:writedata
	wire         mm_interconnect_0_onchip_memory_s1_clken;                  // mm_interconnect_0:onchip_memory_s1_clken -> onchip_memory:clken
	wire         irq_mapper_receiver0_irq;                                  // jtag_uart:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] niosv_m_platform_irq_rx_irq;                               // irq_mapper:sender_irq -> niosv_m:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [axi_lite_pwm:rst_n, irq_mapper:reset, jtag_uart:rst_n, mm_interconnect_0:niosv_m_reset_reset_bridge_in_reset_reset, niosv_m:reset_reset, onchip_memory:reset, onchip_memory:reset2, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                        // rst_controller:reset_req -> [onchip_memory:reset_req, onchip_memory:reset_req2, rst_translator:reset_req_in]

	axi_lite_pwm #(
		.AXI_ADDR_W          (12),
		.AXI_DATA_W          (32),
		.CNT_W               (32),
		.APPLY_ON_PERIOD_END (1)
	) axi_lite_pwm (
		.clk            (clk_clk),                                       //  clock.clk
		.rst_n          (~rst_controller_reset_out_reset),               //  reset.reset_n
		.s_axil_awaddr  (mm_interconnect_0_axi_lite_pwm_s_axil_awaddr),  // s_axil.awaddr
		.s_axil_awvalid (mm_interconnect_0_axi_lite_pwm_s_axil_awvalid), //       .awvalid
		.s_axil_awready (mm_interconnect_0_axi_lite_pwm_s_axil_awready), //       .awready
		.s_axil_wdata   (mm_interconnect_0_axi_lite_pwm_s_axil_wdata),   //       .wdata
		.s_axil_wstrb   (mm_interconnect_0_axi_lite_pwm_s_axil_wstrb),   //       .wstrb
		.s_axil_wready  (mm_interconnect_0_axi_lite_pwm_s_axil_wready),  //       .wready
		.s_axil_wvalid  (mm_interconnect_0_axi_lite_pwm_s_axil_wvalid),  //       .wvalid
		.s_axil_bresp   (mm_interconnect_0_axi_lite_pwm_s_axil_bresp),   //       .bresp
		.s_axil_bvalid  (mm_interconnect_0_axi_lite_pwm_s_axil_bvalid),  //       .bvalid
		.s_axil_bready  (mm_interconnect_0_axi_lite_pwm_s_axil_bready),  //       .bready
		.s_axil_rdata   (mm_interconnect_0_axi_lite_pwm_s_axil_rdata),   //       .rdata
		.s_axil_rresp   (mm_interconnect_0_axi_lite_pwm_s_axil_rresp),   //       .rresp
		.s_axil_rvalid  (mm_interconnect_0_axi_lite_pwm_s_axil_rvalid),  //       .rvalid
		.s_axil_rready  (mm_interconnect_0_axi_lite_pwm_s_axil_rready),  //       .rready
		.s_axil_araddr  (mm_interconnect_0_axi_lite_pwm_s_axil_araddr),  //       .araddr
		.s_axil_arvalid (mm_interconnect_0_axi_lite_pwm_s_axil_arvalid), //       .arvalid
		.s_axil_arready (mm_interconnect_0_axi_lite_pwm_s_axil_arready), //       .arready
		.pwm_raw        (pwm_out_conduit)                                //    pwm.conduit
	);

	altera_avalon_jtag_uart #(
		.readBufferDepth            (64),
		.readIRQThreshold           (8),
		.useRegistersForReadBuffer  (0),
		.useRegistersForWriteBuffer (0),
		.writeBufferDepth           (64),
		.writeIRQThreshold          (8),
		.printingMethod             (0),
		.FIFO_WIDTH                 (8),
		.WR_WIDTHU                  (6),
		.RD_WIDTHU                  (6),
		.write_le                   ("ON"),
		.read_le                    ("ON"),
		.HEX_WRITE_DEPTH_STR        (64),
		.HEX_READ_DEPTH_STR         (64),
		.legacySignalAllow          (0)
	) jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                   //               irq.irq
	);

	system_niosv_m niosv_m (
		.clk                          (clk_clk),                                                //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                         //               reset.reset
		.platform_irq_rx_irq          (niosv_m_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.timer_sw_agent_address       (mm_interconnect_0_niosv_m_timer_sw_agent_address),       //      timer_sw_agent.address
		.timer_sw_agent_byteenable    (mm_interconnect_0_niosv_m_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_read          (mm_interconnect_0_niosv_m_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_niosv_m_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_write         (mm_interconnect_0_niosv_m_timer_sw_agent_write),         //                    .write
		.timer_sw_agent_writedata     (mm_interconnect_0_niosv_m_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_waitrequest   (mm_interconnect_0_niosv_m_timer_sw_agent_waitrequest),   //                    .waitrequest
		.timer_sw_agent_readdatavalid (mm_interconnect_0_niosv_m_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.instruction_manager_awaddr   (niosv_m_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (niosv_m_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (niosv_m_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (niosv_m_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (niosv_m_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (niosv_m_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (niosv_m_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (niosv_m_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (niosv_m_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (niosv_m_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (niosv_m_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (niosv_m_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (niosv_m_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (niosv_m_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (niosv_m_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (niosv_m_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (niosv_m_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (niosv_m_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (niosv_m_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (niosv_m_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (niosv_m_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (niosv_m_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (niosv_m_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (niosv_m_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (niosv_m_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (niosv_m_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (niosv_m_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (niosv_m_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (niosv_m_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (niosv_m_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (niosv_m_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (niosv_m_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (niosv_m_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (niosv_m_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (niosv_m_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (niosv_m_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (niosv_m_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (niosv_m_data_manager_rready),                            //                    .rready
		.dm_agent_address             (mm_interconnect_0_niosv_m_dm_agent_address),             //            dm_agent.address
		.dm_agent_read                (mm_interconnect_0_niosv_m_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_niosv_m_dm_agent_readdata),            //                    .readdata
		.dm_agent_write               (mm_interconnect_0_niosv_m_dm_agent_write),               //                    .write
		.dm_agent_writedata           (mm_interconnect_0_niosv_m_dm_agent_writedata),           //                    .writedata
		.dm_agent_waitrequest         (mm_interconnect_0_niosv_m_dm_agent_waitrequest),         //                    .waitrequest
		.dm_agent_readdatavalid       (mm_interconnect_0_niosv_m_dm_agent_readdatavalid)        //                    .readdatavalid
	);

	system_onchip_memory onchip_memory (
		.clk         (clk_clk),                                       //   clk1.clk
		.address     (mm_interconnect_0_onchip_memory_s1_address),    //     s1.address
		.clken       (mm_interconnect_0_onchip_memory_s1_clken),      //       .clken
		.chipselect  (mm_interconnect_0_onchip_memory_s1_chipselect), //       .chipselect
		.write       (mm_interconnect_0_onchip_memory_s1_write),      //       .write
		.readdata    (mm_interconnect_0_onchip_memory_s1_readdata),   //       .readdata
		.writedata   (mm_interconnect_0_onchip_memory_s1_writedata),  //       .writedata
		.byteenable  (mm_interconnect_0_onchip_memory_s1_byteenable), //       .byteenable
		.reset       (rst_controller_reset_out_reset),                // reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),            //       .reset_req
		.address2    (mm_interconnect_0_onchip_memory_s2_address),    //     s2.address
		.chipselect2 (mm_interconnect_0_onchip_memory_s2_chipselect), //       .chipselect
		.clken2      (mm_interconnect_0_onchip_memory_s2_clken),      //       .clken
		.write2      (mm_interconnect_0_onchip_memory_s2_write),      //       .write
		.readdata2   (mm_interconnect_0_onchip_memory_s2_readdata),   //       .readdata
		.writedata2  (mm_interconnect_0_onchip_memory_s2_writedata),  //       .writedata
		.byteenable2 (mm_interconnect_0_onchip_memory_s2_byteenable), //       .byteenable
		.clk2        (clk_clk),                                       //   clk2.clk
		.reset2      (rst_controller_reset_out_reset),                // reset2.reset
		.reset_req2  (rst_controller_reset_out_reset_req),            //       .reset_req
		.freeze      (1'b0)                                           // (terminated)
	);

	system_mm_interconnect_0 mm_interconnect_0 (
		.axi_lite_pwm_s_axil_awaddr                (mm_interconnect_0_axi_lite_pwm_s_axil_awaddr),              //                 axi_lite_pwm_s_axil.awaddr
		.axi_lite_pwm_s_axil_awprot                (),                                                          //                                    .awprot
		.axi_lite_pwm_s_axil_awvalid               (mm_interconnect_0_axi_lite_pwm_s_axil_awvalid),             //                                    .awvalid
		.axi_lite_pwm_s_axil_awready               (mm_interconnect_0_axi_lite_pwm_s_axil_awready),             //                                    .awready
		.axi_lite_pwm_s_axil_wdata                 (mm_interconnect_0_axi_lite_pwm_s_axil_wdata),               //                                    .wdata
		.axi_lite_pwm_s_axil_wstrb                 (mm_interconnect_0_axi_lite_pwm_s_axil_wstrb),               //                                    .wstrb
		.axi_lite_pwm_s_axil_wvalid                (mm_interconnect_0_axi_lite_pwm_s_axil_wvalid),              //                                    .wvalid
		.axi_lite_pwm_s_axil_wready                (mm_interconnect_0_axi_lite_pwm_s_axil_wready),              //                                    .wready
		.axi_lite_pwm_s_axil_bresp                 (mm_interconnect_0_axi_lite_pwm_s_axil_bresp),               //                                    .bresp
		.axi_lite_pwm_s_axil_bvalid                (mm_interconnect_0_axi_lite_pwm_s_axil_bvalid),              //                                    .bvalid
		.axi_lite_pwm_s_axil_bready                (mm_interconnect_0_axi_lite_pwm_s_axil_bready),              //                                    .bready
		.axi_lite_pwm_s_axil_araddr                (mm_interconnect_0_axi_lite_pwm_s_axil_araddr),              //                                    .araddr
		.axi_lite_pwm_s_axil_arprot                (),                                                          //                                    .arprot
		.axi_lite_pwm_s_axil_arvalid               (mm_interconnect_0_axi_lite_pwm_s_axil_arvalid),             //                                    .arvalid
		.axi_lite_pwm_s_axil_arready               (mm_interconnect_0_axi_lite_pwm_s_axil_arready),             //                                    .arready
		.axi_lite_pwm_s_axil_rdata                 (mm_interconnect_0_axi_lite_pwm_s_axil_rdata),               //                                    .rdata
		.axi_lite_pwm_s_axil_rresp                 (mm_interconnect_0_axi_lite_pwm_s_axil_rresp),               //                                    .rresp
		.axi_lite_pwm_s_axil_rvalid                (mm_interconnect_0_axi_lite_pwm_s_axil_rvalid),              //                                    .rvalid
		.axi_lite_pwm_s_axil_rready                (mm_interconnect_0_axi_lite_pwm_s_axil_rready),              //                                    .rready
		.niosv_m_data_manager_awaddr               (niosv_m_data_manager_awaddr),                               //                niosv_m_data_manager.awaddr
		.niosv_m_data_manager_awprot               (niosv_m_data_manager_awprot),                               //                                    .awprot
		.niosv_m_data_manager_awvalid              (niosv_m_data_manager_awvalid),                              //                                    .awvalid
		.niosv_m_data_manager_awready              (niosv_m_data_manager_awready),                              //                                    .awready
		.niosv_m_data_manager_wdata                (niosv_m_data_manager_wdata),                                //                                    .wdata
		.niosv_m_data_manager_wstrb                (niosv_m_data_manager_wstrb),                                //                                    .wstrb
		.niosv_m_data_manager_wvalid               (niosv_m_data_manager_wvalid),                               //                                    .wvalid
		.niosv_m_data_manager_wready               (niosv_m_data_manager_wready),                               //                                    .wready
		.niosv_m_data_manager_bresp                (niosv_m_data_manager_bresp),                                //                                    .bresp
		.niosv_m_data_manager_bvalid               (niosv_m_data_manager_bvalid),                               //                                    .bvalid
		.niosv_m_data_manager_bready               (niosv_m_data_manager_bready),                               //                                    .bready
		.niosv_m_data_manager_araddr               (niosv_m_data_manager_araddr),                               //                                    .araddr
		.niosv_m_data_manager_arprot               (niosv_m_data_manager_arprot),                               //                                    .arprot
		.niosv_m_data_manager_arvalid              (niosv_m_data_manager_arvalid),                              //                                    .arvalid
		.niosv_m_data_manager_arready              (niosv_m_data_manager_arready),                              //                                    .arready
		.niosv_m_data_manager_rdata                (niosv_m_data_manager_rdata),                                //                                    .rdata
		.niosv_m_data_manager_rresp                (niosv_m_data_manager_rresp),                                //                                    .rresp
		.niosv_m_data_manager_rvalid               (niosv_m_data_manager_rvalid),                               //                                    .rvalid
		.niosv_m_data_manager_rready               (niosv_m_data_manager_rready),                               //                                    .rready
		.niosv_m_instruction_manager_awaddr        (niosv_m_instruction_manager_awaddr),                        //         niosv_m_instruction_manager.awaddr
		.niosv_m_instruction_manager_awprot        (niosv_m_instruction_manager_awprot),                        //                                    .awprot
		.niosv_m_instruction_manager_awvalid       (niosv_m_instruction_manager_awvalid),                       //                                    .awvalid
		.niosv_m_instruction_manager_awready       (niosv_m_instruction_manager_awready),                       //                                    .awready
		.niosv_m_instruction_manager_wdata         (niosv_m_instruction_manager_wdata),                         //                                    .wdata
		.niosv_m_instruction_manager_wstrb         (niosv_m_instruction_manager_wstrb),                         //                                    .wstrb
		.niosv_m_instruction_manager_wvalid        (niosv_m_instruction_manager_wvalid),                        //                                    .wvalid
		.niosv_m_instruction_manager_wready        (niosv_m_instruction_manager_wready),                        //                                    .wready
		.niosv_m_instruction_manager_bresp         (niosv_m_instruction_manager_bresp),                         //                                    .bresp
		.niosv_m_instruction_manager_bvalid        (niosv_m_instruction_manager_bvalid),                        //                                    .bvalid
		.niosv_m_instruction_manager_bready        (niosv_m_instruction_manager_bready),                        //                                    .bready
		.niosv_m_instruction_manager_araddr        (niosv_m_instruction_manager_araddr),                        //                                    .araddr
		.niosv_m_instruction_manager_arprot        (niosv_m_instruction_manager_arprot),                        //                                    .arprot
		.niosv_m_instruction_manager_arvalid       (niosv_m_instruction_manager_arvalid),                       //                                    .arvalid
		.niosv_m_instruction_manager_arready       (niosv_m_instruction_manager_arready),                       //                                    .arready
		.niosv_m_instruction_manager_rdata         (niosv_m_instruction_manager_rdata),                         //                                    .rdata
		.niosv_m_instruction_manager_rresp         (niosv_m_instruction_manager_rresp),                         //                                    .rresp
		.niosv_m_instruction_manager_rvalid        (niosv_m_instruction_manager_rvalid),                        //                                    .rvalid
		.niosv_m_instruction_manager_rready        (niosv_m_instruction_manager_rready),                        //                                    .rready
		.clk_0_clk_clk                             (clk_clk),                                                   //                           clk_0_clk.clk
		.niosv_m_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                            // niosv_m_reset_reset_bridge_in_reset.reset
		.jtag_uart_avalon_jtag_slave_address       (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //         jtag_uart_avalon_jtag_slave.address
		.jtag_uart_avalon_jtag_slave_write         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),       //                                    .write
		.jtag_uart_avalon_jtag_slave_read          (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),        //                                    .read
		.jtag_uart_avalon_jtag_slave_readdata      (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                                    .readdata
		.jtag_uart_avalon_jtag_slave_writedata     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                                    .writedata
		.jtag_uart_avalon_jtag_slave_waitrequest   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                                    .waitrequest
		.jtag_uart_avalon_jtag_slave_chipselect    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  //                                    .chipselect
		.niosv_m_dm_agent_address                  (mm_interconnect_0_niosv_m_dm_agent_address),                //                    niosv_m_dm_agent.address
		.niosv_m_dm_agent_write                    (mm_interconnect_0_niosv_m_dm_agent_write),                  //                                    .write
		.niosv_m_dm_agent_read                     (mm_interconnect_0_niosv_m_dm_agent_read),                   //                                    .read
		.niosv_m_dm_agent_readdata                 (mm_interconnect_0_niosv_m_dm_agent_readdata),               //                                    .readdata
		.niosv_m_dm_agent_writedata                (mm_interconnect_0_niosv_m_dm_agent_writedata),              //                                    .writedata
		.niosv_m_dm_agent_readdatavalid            (mm_interconnect_0_niosv_m_dm_agent_readdatavalid),          //                                    .readdatavalid
		.niosv_m_dm_agent_waitrequest              (mm_interconnect_0_niosv_m_dm_agent_waitrequest),            //                                    .waitrequest
		.niosv_m_timer_sw_agent_address            (mm_interconnect_0_niosv_m_timer_sw_agent_address),          //              niosv_m_timer_sw_agent.address
		.niosv_m_timer_sw_agent_write              (mm_interconnect_0_niosv_m_timer_sw_agent_write),            //                                    .write
		.niosv_m_timer_sw_agent_read               (mm_interconnect_0_niosv_m_timer_sw_agent_read),             //                                    .read
		.niosv_m_timer_sw_agent_readdata           (mm_interconnect_0_niosv_m_timer_sw_agent_readdata),         //                                    .readdata
		.niosv_m_timer_sw_agent_writedata          (mm_interconnect_0_niosv_m_timer_sw_agent_writedata),        //                                    .writedata
		.niosv_m_timer_sw_agent_byteenable         (mm_interconnect_0_niosv_m_timer_sw_agent_byteenable),       //                                    .byteenable
		.niosv_m_timer_sw_agent_readdatavalid      (mm_interconnect_0_niosv_m_timer_sw_agent_readdatavalid),    //                                    .readdatavalid
		.niosv_m_timer_sw_agent_waitrequest        (mm_interconnect_0_niosv_m_timer_sw_agent_waitrequest),      //                                    .waitrequest
		.onchip_memory_s1_address                  (mm_interconnect_0_onchip_memory_s1_address),                //                    onchip_memory_s1.address
		.onchip_memory_s1_write                    (mm_interconnect_0_onchip_memory_s1_write),                  //                                    .write
		.onchip_memory_s1_readdata                 (mm_interconnect_0_onchip_memory_s1_readdata),               //                                    .readdata
		.onchip_memory_s1_writedata                (mm_interconnect_0_onchip_memory_s1_writedata),              //                                    .writedata
		.onchip_memory_s1_byteenable               (mm_interconnect_0_onchip_memory_s1_byteenable),             //                                    .byteenable
		.onchip_memory_s1_chipselect               (mm_interconnect_0_onchip_memory_s1_chipselect),             //                                    .chipselect
		.onchip_memory_s1_clken                    (mm_interconnect_0_onchip_memory_s1_clken),                  //                                    .clken
		.onchip_memory_s2_address                  (mm_interconnect_0_onchip_memory_s2_address),                //                    onchip_memory_s2.address
		.onchip_memory_s2_write                    (mm_interconnect_0_onchip_memory_s2_write),                  //                                    .write
		.onchip_memory_s2_readdata                 (mm_interconnect_0_onchip_memory_s2_readdata),               //                                    .readdata
		.onchip_memory_s2_writedata                (mm_interconnect_0_onchip_memory_s2_writedata),              //                                    .writedata
		.onchip_memory_s2_byteenable               (mm_interconnect_0_onchip_memory_s2_byteenable),             //                                    .byteenable
		.onchip_memory_s2_chipselect               (mm_interconnect_0_onchip_memory_s2_chipselect),             //                                    .chipselect
		.onchip_memory_s2_clken                    (mm_interconnect_0_onchip_memory_s2_clken)                   //                                    .clken
	);

	system_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (niosv_m_platform_irq_rx_irq)     //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
